title: Mai Waziry
logo:  # Replace with your logo path, or remove the line if no logo
description:   # Optional, but recommended
show_downloads: true

remote_theme: pages-themes/jekyll-theme-slate

plugins:
  - jekyll-remote-theme  # Add this line to the plugins list if you already have one
